linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable-all: false
run:
  timeout: 5m
  tests: true
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
