// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/pb/torana.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single turn in a chat conversation.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// JSON array of multimodal parts (e.g. vision)
	ContentPartsJson  []byte      `protobuf:"bytes,3,opt,name=content_parts_json,json=contentPartsJson,proto3" json:"content_parts_json,omitempty"`
	Thinking          string      `protobuf:"bytes,4,opt,name=thinking,proto3" json:"thinking,omitempty"`
	ThinkingSignature string      `protobuf:"bytes,5,opt,name=thinking_signature,json=thinkingSignature,proto3" json:"thinking_signature,omitempty"`
	ToolCalls         []*ToolCall `protobuf:"bytes,6,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId        string      `protobuf:"bytes,7,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName          string      `protobuf:"bytes,8,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_pb_torana_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentPartsJson() []byte {
	if x != nil {
		return x.ContentPartsJson
	}
	return nil
}

func (x *Message) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *Message) GetThinkingSignature() string {
	if x != nil {
		return x.ThinkingSignature
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

// An assistant's request to invoke a tool.
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson []byte                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_pkg_pb_torana_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

// Describes a function available to the model.
type ToolDef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson []byte                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	Strict         bool                   `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolDef) Reset() {
	*x = ToolDef{}
	mi := &file_pkg_pb_torana_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDef) ProtoMessage() {}

func (x *ToolDef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDef.ProtoReflect.Descriptor instead.
func (*ToolDef) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDef) GetParametersJson() []byte {
	if x != nil {
		return x.ParametersJson
	}
	return nil
}

func (x *ToolDef) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

// Canonical representation of a chat completion request.
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*ToolDef             `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Stream        bool                   `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	Temperature   *float64               `protobuf:"fixed64,6,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP          *float64               `protobuf:"fixed64,7,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	StopSequences []string               `protobuf:"bytes,8,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	// Unparsed provider fields (passed transparently as JSON)
	ProviderExtensionsJson []byte `protobuf:"bytes,9,opt,name=provider_extensions_json,json=providerExtensionsJson,proto3" json:"provider_extensions_json,omitempty"`
	// Proxy-internal metadata shared between hooks. Not serialized to wire.
	ToranaMetaJson []byte `protobuf:"bytes,10,opt,name=torana_meta_json,json=toranaMetaJson,proto3" json:"torana_meta_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_pkg_pb_torana_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetTools() []*ToolDef {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *ChatRequest) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *ChatRequest) GetProviderExtensionsJson() []byte {
	if x != nil {
		return x.ProviderExtensionsJson
	}
	return nil
}

func (x *ChatRequest) GetToranaMetaJson() []byte {
	if x != nil {
		return x.ToranaMetaJson
	}
	return nil
}

type ToolCallStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallStart) Reset() {
	*x = ToolCallStart{}
	mi := &file_pkg_pb_torana_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallStart) ProtoMessage() {}

func (x *ToolCallStart) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallStart.ProtoReflect.Descriptor instead.
func (*ToolCallStart) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCallStart) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ToolCallDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ArgumentsDelta string                 `protobuf:"bytes,2,opt,name=arguments_delta,json=argumentsDelta,proto3" json:"arguments_delta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCallDelta) Reset() {
	*x = ToolCallDelta{}
	mi := &file_pkg_pb_torana_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDelta) ProtoMessage() {}

func (x *ToolCallDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDelta.ProtoReflect.Descriptor instead.
func (*ToolCallDelta) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallDelta) GetArgumentsDelta() string {
	if x != nil {
		return x.ArgumentsDelta
	}
	return ""
}

type ToolCallEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallEnd) Reset() {
	*x = ToolCallEnd{}
	mi := &file_pkg_pb_torana_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEnd) ProtoMessage() {}

func (x *ToolCallEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEnd.ProtoReflect.Descriptor instead.
func (*ToolCallEnd) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCallEnd) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_pkg_pb_torana_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{7}
}

func (x *StreamError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUsage) Reset() {
	*x = StreamUsage{}
	mi := &file_pkg_pb_torana_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUsage) ProtoMessage() {}

func (x *StreamUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUsage.ProtoReflect.Descriptor instead.
func (*StreamUsage) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{8}
}

func (x *StreamUsage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *StreamUsage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamEvent_TextDelta
	//	*StreamEvent_ThinkingDelta
	//	*StreamEvent_ToolCallStart
	//	*StreamEvent_ToolCallDelta
	//	*StreamEvent_ToolCallEnd
	//	*StreamEvent_FinishReason
	//	*StreamEvent_Usage
	//	*StreamEvent_Error
	Event         isStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_pkg_pb_torana_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_torana_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_pkg_pb_torana_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEvent) GetEvent() isStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEvent) GetTextDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_TextDelta); ok {
			return x.TextDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetThinkingDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ThinkingDelta); ok {
			return x.ThinkingDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetToolCallStart() *ToolCallStart {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallStart); ok {
			return x.ToolCallStart
		}
	}
	return nil
}

func (x *StreamEvent) GetToolCallDelta() *ToolCallDelta {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallDelta); ok {
			return x.ToolCallDelta
		}
	}
	return nil
}

func (x *StreamEvent) GetToolCallEnd() *ToolCallEnd {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallEnd); ok {
			return x.ToolCallEnd
		}
	}
	return nil
}

func (x *StreamEvent) GetFinishReason() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_FinishReason); ok {
			return x.FinishReason
		}
	}
	return ""
}

func (x *StreamEvent) GetUsage() *StreamUsage {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *StreamEvent) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_TextDelta struct {
	TextDelta string `protobuf:"bytes,1,opt,name=text_delta,json=textDelta,proto3,oneof"`
}

type StreamEvent_ThinkingDelta struct {
	ThinkingDelta string `protobuf:"bytes,2,opt,name=thinking_delta,json=thinkingDelta,proto3,oneof"`
}

type StreamEvent_ToolCallStart struct {
	ToolCallStart *ToolCallStart `protobuf:"bytes,3,opt,name=tool_call_start,json=toolCallStart,proto3,oneof"`
}

type StreamEvent_ToolCallDelta struct {
	ToolCallDelta *ToolCallDelta `protobuf:"bytes,4,opt,name=tool_call_delta,json=toolCallDelta,proto3,oneof"`
}

type StreamEvent_ToolCallEnd struct {
	ToolCallEnd *ToolCallEnd `protobuf:"bytes,5,opt,name=tool_call_end,json=toolCallEnd,proto3,oneof"`
}

type StreamEvent_FinishReason struct {
	FinishReason string `protobuf:"bytes,6,opt,name=finish_reason,json=finishReason,proto3,oneof"`
}

type StreamEvent_Usage struct {
	Usage *StreamUsage `protobuf:"bytes,7,opt,name=usage,proto3,oneof"`
}

type StreamEvent_Error struct {
	Error *StreamError `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

func (*StreamEvent_TextDelta) isStreamEvent_Event() {}

func (*StreamEvent_ThinkingDelta) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallStart) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallDelta) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallEnd) isStreamEvent_Event() {}

func (*StreamEvent_FinishReason) isStreamEvent_Event() {}

func (*StreamEvent_Usage) isStreamEvent_Event() {}

func (*StreamEvent_Error) isStreamEvent_Event() {}

var File_pkg_pb_torana_proto protoreflect.FileDescriptor

const file_pkg_pb_torana_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/pb/torana.proto\x12\ttorana.v1\"\xa3\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12,\n" +
	"\x12content_parts_json\x18\x03 \x01(\fR\x10contentPartsJson\x12\x1a\n" +
	"\bthinking\x18\x04 \x01(\tR\bthinking\x12-\n" +
	"\x12thinking_signature\x18\x05 \x01(\tR\x11thinkingSignature\x122\n" +
	"\n" +
	"tool_calls\x18\x06 \x03(\v2\x13.torana.v1.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\a \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\b \x01(\tR\btoolName\"U\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\"\x80\x01\n" +
	"\aToolDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\fR\x0eparametersJson\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\"\xae\x03\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12.\n" +
	"\bmessages\x18\x02 \x03(\v2\x12.torana.v1.MessageR\bmessages\x12(\n" +
	"\x05tools\x18\x03 \x03(\v2\x12.torana.v1.ToolDefR\x05tools\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\x12\"\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05H\x00R\tmaxTokens\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\x06 \x01(\x01H\x01R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\a \x01(\x01H\x02R\x04topP\x88\x01\x01\x12%\n" +
	"\x0estop_sequences\x18\b \x03(\tR\rstopSequences\x128\n" +
	"\x18provider_extensions_json\x18\t \x01(\fR\x16providerExtensionsJson\x12(\n" +
	"\x10torana_meta_json\x18\n" +
	" \x01(\fR\x0etoranaMetaJsonB\r\n" +
	"\v_max_tokensB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_p\"I\n" +
	"\rToolCallStart\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"N\n" +
	"\rToolCallDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12'\n" +
	"\x0farguments_delta\x18\x02 \x01(\tR\x0eargumentsDelta\"#\n" +
	"\vToolCallEnd\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\";\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\vStreamUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\"\xad\x03\n" +
	"\vStreamEvent\x12\x1f\n" +
	"\n" +
	"text_delta\x18\x01 \x01(\tH\x00R\ttextDelta\x12'\n" +
	"\x0ethinking_delta\x18\x02 \x01(\tH\x00R\rthinkingDelta\x12B\n" +
	"\x0ftool_call_start\x18\x03 \x01(\v2\x18.torana.v1.ToolCallStartH\x00R\rtoolCallStart\x12B\n" +
	"\x0ftool_call_delta\x18\x04 \x01(\v2\x18.torana.v1.ToolCallDeltaH\x00R\rtoolCallDelta\x12<\n" +
	"\rtool_call_end\x18\x05 \x01(\v2\x16.torana.v1.ToolCallEndH\x00R\vtoolCallEnd\x12%\n" +
	"\rfinish_reason\x18\x06 \x01(\tH\x00R\ffinishReason\x12.\n" +
	"\x05usage\x18\a \x01(\v2\x16.torana.v1.StreamUsageH\x00R\x05usage\x12.\n" +
	"\x05error\x18\b \x01(\v2\x16.torana.v1.StreamErrorH\x00R\x05errorB\a\n" +
	"\x05eventB+Z)github.com/torana-edge/torana-edge/pkg/pbb\x06proto3"

var (
	file_pkg_pb_torana_proto_rawDescOnce sync.Once
	file_pkg_pb_torana_proto_rawDescData []byte
)

func file_pkg_pb_torana_proto_rawDescGZIP() []byte {
	file_pkg_pb_torana_proto_rawDescOnce.Do(func() {
		file_pkg_pb_torana_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_torana_proto_rawDesc), len(file_pkg_pb_torana_proto_rawDesc)))
	})
	return file_pkg_pb_torana_proto_rawDescData
}

var file_pkg_pb_torana_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_pb_torana_proto_goTypes = []any{
	(*Message)(nil),       // 0: torana.v1.Message
	(*ToolCall)(nil),      // 1: torana.v1.ToolCall
	(*ToolDef)(nil),       // 2: torana.v1.ToolDef
	(*ChatRequest)(nil),   // 3: torana.v1.ChatRequest
	(*ToolCallStart)(nil), // 4: torana.v1.ToolCallStart
	(*ToolCallDelta)(nil), // 5: torana.v1.ToolCallDelta
	(*ToolCallEnd)(nil),   // 6: torana.v1.ToolCallEnd
	(*StreamError)(nil),   // 7: torana.v1.StreamError
	(*StreamUsage)(nil),   // 8: torana.v1.StreamUsage
	(*StreamEvent)(nil),   // 9: torana.v1.StreamEvent
}
var file_pkg_pb_torana_proto_depIdxs = []int32{
	1, // 0: torana.v1.Message.tool_calls:type_name -> torana.v1.ToolCall
	0, // 1: torana.v1.ChatRequest.messages:type_name -> torana.v1.Message
	2, // 2: torana.v1.ChatRequest.tools:type_name -> torana.v1.ToolDef
	4, // 3: torana.v1.StreamEvent.tool_call_start:type_name -> torana.v1.ToolCallStart
	5, // 4: torana.v1.StreamEvent.tool_call_delta:type_name -> torana.v1.ToolCallDelta
	6, // 5: torana.v1.StreamEvent.tool_call_end:type_name -> torana.v1.ToolCallEnd
	8, // 6: torana.v1.StreamEvent.usage:type_name -> torana.v1.StreamUsage
	7, // 7: torana.v1.StreamEvent.error:type_name -> torana.v1.StreamError
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_pb_torana_proto_init() }
func file_pkg_pb_torana_proto_init() {
	if File_pkg_pb_torana_proto != nil {
		return
	}
	file_pkg_pb_torana_proto_msgTypes[3].OneofWrappers = []any{}
	file_pkg_pb_torana_proto_msgTypes[9].OneofWrappers = []any{
		(*StreamEvent_TextDelta)(nil),
		(*StreamEvent_ThinkingDelta)(nil),
		(*StreamEvent_ToolCallStart)(nil),
		(*StreamEvent_ToolCallDelta)(nil),
		(*StreamEvent_ToolCallEnd)(nil),
		(*StreamEvent_FinishReason)(nil),
		(*StreamEvent_Usage)(nil),
		(*StreamEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_torana_proto_rawDesc), len(file_pkg_pb_torana_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_torana_proto_goTypes,
		DependencyIndexes: file_pkg_pb_torana_proto_depIdxs,
		MessageInfos:      file_pkg_pb_torana_proto_msgTypes,
	}.Build()
	File_pkg_pb_torana_proto = out.File
	file_pkg_pb_torana_proto_goTypes = nil
	file_pkg_pb_torana_proto_depIdxs = nil
}
